FROM python:3.12-slim
RUN apt-get update && apt-get install -y \
    libsdl2-dev \
    libsdl2-image-dev \
    libsdl2-mixer-dev \
    libsdl2-ttf-dev \
    libgl1 \
    libmtdev1 \
    xvfb \
    alsa-utils \
    portaudio19-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
RUN mkdir -p /tmp/.X11-unix && chmod 1777 /tmp/.X11-unix
